default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: demjhonsnelby
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: ruby_picturer
